postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: 5
  username: <%=ENV['USER']%>

development:
  <<: *postgresql
  database: wamlibrary

test:
  <<: *postgresql
  database: wamlibrary_test

# production:
#   <<: *postgresql
#   database: wamlibrary_prod
